AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless pipeline project

Resources:

  ArtifactS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: !Sub PipelineryCodePipelinePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Resource: "*"
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactS3Bucket}/*
                  - !Sub arn:aws:s3:::${ArtifactS3Bucket}
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:ListBucket

  CloudformationDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: !Sub PipelineryCloudformationPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - "*"

  PipelineTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/triggers/pipeline/
      Handler: app.handler
      Runtime: python3.8
      Timeout: 300
      Environment:
        Variables:
          CODEPIPELINE_ROLE_ARN: !GetAtt CodePipelineRole.Arn
          CLOUDFORMATION_ROLE_ARN: !GetAtt CloudformationDeployerRole.Arn
          ARTIFACT_BUCKET: !Ref ArtifactS3Bucket
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - '*'
            - Effect: Allow
              Action: iam:PassRole
              Resource: '*'
            - Effect: Allow
              Action:
                - codepipeline:*
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - 'logs:PutLogEvents'
                - 'logs:DescribeLogStreams'
                - 'logs:DescribeLogGroups'
              Resource:
                - '*'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /triggers/pipeline
            Method: post

  ExecutionStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/executions/status/
      Handler: app.handler
      Runtime: python3.8
      Timeout: 60
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: iam:PassRole
              Resource: '*'
            - Effect: Allow
              Action:
                - codepipeline:*
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - 'logs:PutLogEvents'
                - 'logs:DescribeLogStreams'
                - 'logs:DescribeLogGroups'
              Resource:
                - '*'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /execution/status/{id}
            Method: get
